apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: items-app
  labels:
    app: items-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: items-backend
  template:
    metadata:
      labels:
        app: items-backend
    spec:
      containers:
      - name: backend
        image: your-registry/items-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5