apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: items-app
spec:
  selector:
    app: items-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP