apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: items-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: your-registry/items-frontend
    newTag: latest

configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_URL=http://backend-service:8080

secretGenerator:
  - name: frontend-secrets
    behavior: merge
    literals:
      #- API_SECRET=your-secret-key-here