apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: items-app
  labels:
    app: items-frontend
    version: v1
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: items-frontend
  template:
    metadata:
      labels:
        app: items-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: your-registry/items-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        - name: NUXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NUXT_PUBLIC_API_URL
        - name: NUXT_PUBLIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NUXT_PUBLIC_APP_NAME
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: API_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30