apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: items-app
  labels:
    app: items-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: items-frontend
  template:
    metadata:
      labels:
        app: items-frontend
    spec:
      containers:
      - name: frontend
        image: your-registry/items-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: frontend-config
        - secretRef:
            name: frontend-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5